<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-23T22:02:51 IST" name="appseConnectV1" finished-at="2022-05-23T22:04:22 IST" duration-ms="90744">
    <groups>
    </groups>
    <test started-at="2022-05-23T22:02:51 IST" name="appseConnect Test" finished-at="2022-05-23T22:04:22 IST" duration-ms="90744">
      <class name="com.appseConnect.testCases.TC_LoginTestDDT_002">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.appseConnect.testCases.TC_LoginTestDDT_002@52719fb6]" started-at="2022-05-23T22:03:23 IST" name="setUp" finished-at="2022-05-23T22:03:33 IST" duration-ms="10740" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTestDDT(java.lang.String,java.lang.String)[pri:0, instance:com.appseConnect.testCases.TC_LoginTestDDT_002@52719fb6]" started-at="2022-05-23T22:03:34 IST" name="loginTestDDT" data-provider="LoginData" finished-at="2022-05-23T22:03:55 IST" duration-ms="20402" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[debashree.p@insync.co.in]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Efgh.1234]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestDDT -->
        <test-method signature="loginTestDDT(java.lang.String,java.lang.String)[pri:0, instance:com.appseConnect.testCases.TC_LoginTestDDT_002@52719fb6]" started-at="2022-05-23T22:03:55 IST" name="loginTestDDT" data-provider="LoginData" finished-at="2022-05-23T22:03:59 IST" duration-ms="4140" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[debashree.p@insync.co.in]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Efgh.1234xxxx]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.appseConnect.testCases.TC_LoginTestDDT_002.loginTestDDT(TC_LoginTestDDT_002.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestDDT -->
        <test-method signature="loginTestDDT(java.lang.String,java.lang.String)[pri:0, instance:com.appseConnect.testCases.TC_LoginTestDDT_002@52719fb6]" started-at="2022-05-23T22:03:59 IST" name="loginTestDDT" data-provider="LoginData" finished-at="2022-05-23T22:04:08 IST" duration-ms="9209" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[rio1@yopmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abcd.1234]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestDDT -->
        <test-method signature="loginTestDDT(java.lang.String,java.lang.String)[pri:0, instance:com.appseConnect.testCases.TC_LoginTestDDT_002@52719fb6]" started-at="2022-05-23T22:04:08 IST" name="loginTestDDT" data-provider="LoginData" finished-at="2022-05-23T22:04:18 IST" duration-ms="10027" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[debashree.p@insync.co.in]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Efgh.1234]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestDDT -->
        <test-method signature="loginTestDDT(java.lang.String,java.lang.String)[pri:0, instance:com.appseConnect.testCases.TC_LoginTestDDT_002@52719fb6]" started-at="2022-05-23T22:04:18 IST" name="loginTestDDT" data-provider="LoginData" finished-at="2022-05-23T22:04:21 IST" duration-ms="3083" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[debashree.p@insync.co.inxxxxxxx]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Efgh.1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.appseConnect.testCases.TC_LoginTestDDT_002.loginTestDDT(TC_LoginTestDDT_002.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestDDT -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.appseConnect.testCases.TC_LoginTestDDT_002@52719fb6]" started-at="2022-05-23T22:04:21 IST" name="tearDown" finished-at="2022-05-23T22:04:22 IST" duration-ms="744" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.appseConnect.testCases.TC_LoginTestDDT_002 -->
      <class name="com.appseConnect.testCases.TC_LoginTest_001">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.appseConnect.testCases.TC_LoginTest_001@5d534f5d]" started-at="2022-05-23T22:02:52 IST" name="setUp" finished-at="2022-05-23T22:03:04 IST" duration-ms="12730" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTest()[pri:0, instance:com.appseConnect.testCases.TC_LoginTest_001@5d534f5d]" started-at="2022-05-23T22:03:04 IST" name="loginTest" finished-at="2022-05-23T22:03:22 IST" duration-ms="17583" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.appseConnect.testCases.TC_LoginTest_001@5d534f5d]" started-at="2022-05-23T22:03:22 IST" name="tearDown" finished-at="2022-05-23T22:03:23 IST" duration-ms="733" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.appseConnect.testCases.TC_LoginTest_001 -->
    </test> <!-- appseConnect Test -->
  </suite> <!-- appseConnectV1 -->
</testng-results>
